services:
  mongo-auth:
    image: mongo:7
    container_name: mongo-auth
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: authdb

  mongo-restaurant:
    image: mongo:7
    container_name: mongo-restaurant
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: restaurantdb

  mongo-menu:
    image: mongo:7
    container_name: mongo-menu
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: menudb

  mongo-order:
    image: mongo:7
    container_name: mongo-order
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_DATABASE: orderdb

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
      NODE_ENV: production
      MONGO_URI: mongodb://mongo-auth:27017/authdb
      JWT_SECRET: supersecretjwtkey123kubekitchen
      JWT_EXPIRES_IN: 7d
    depends_on:
      - mongo-auth

  restaurant-service:
    build:
      context: ./services/restaurant-service
      dockerfile: Dockerfile
    container_name: restaurant-service
    restart: always
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      NODE_ENV: production
      MONGO_URI: mongodb://mongo-restaurant:27017/restaurantdb
      JWT_SECRET: supersecretjwtkey123kubekitchen
    depends_on:
      - mongo-restaurant

  menu-service:
    build:
      context: ./services/menu-service
      dockerfile: Dockerfile
    container_name: menu-service
    restart: always
    ports:
      - "4003:4003"
    environment:
      PORT: 4003
      NODE_ENV: production
      MONGO_URI: mongodb://mongo-menu:27017/menudb
      JWT_SECRET: supersecretjwtkey123kubekitchen
    depends_on:
      - mongo-menu

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: always
    ports:
      - "4004:4004"
    environment:
      PORT: 4004
      NODE_ENV: production
      MENU_SERVICE_URL: http://menu-service:4003
      MONGO_URI: mongodb://mongo-order:27017/orderdb
      JWT_SECRET: supersecretjwtkey123kubekitchen
    depends_on:
      - mongo-order

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:8080"
    environment:
      NODE_ENV: production
    depends_on:
      - auth-service
      - restaurant-service
      - menu-service
      - order-service