apiVersion: v1
kind: Secret
metadata:
  name: kubekitchen-secrets
  namespace: kubekitchen-dev
  labels:
    project: kubekitchen
    environment: dev
type: Opaque
stringData:
  JWT_SECRET: "dev-jwt-secret-change-this-256bit-key"
  MONGO_AUTH_URI: "mongodb://mongodb-auth-0.mongodb-auth-headless.kubekitchen-dev.svc.cluster.local:27017/authdb"
  MONGO_RESTAURANT_URI: "mongodb://mongodb-restaurant-0.mongodb-restaurant-headless.kubekitchen-dev.svc.cluster.local:27017/restaurantdb"
  MONGO_MENU_URI: "mongodb://mongodb-menu-0.mongodb-menu-headless.kubekitchen-dev.svc.cluster.local:27017/menudb"
  MONGO_ORDER_URI: "mongodb://mongodb-order-0.mongodb-order-headless.kubekitchen-dev.svc.cluster.local:27017/orderdb"