apiVersion: v1
kind: Secret
metadata:
  name: kubekitchen-secrets
  namespace: kubekitchen-prod
  labels:
    project: kubekitchen
    environment: prod
type: Opaque
stringData:
  JWT_SECRET: "prod-jwt-secret-REPLACE-WITH-STRONG-256BIT-SECRET"
  MONGO_AUTH_URI: "mongodb://mongodb-auth-0.mongodb-auth-headless.kubekitchen-prod.svc.cluster.local:27017/authdb"
  MONGO_RESTAURANT_URI: "mongodb://mongodb-restaurant-0.mongodb-restaurant-headless.kubekitchen-prod.svc.cluster.local:27017/restaurantdb"
  MONGO_MENU_URI: "mongodb://mongodb-menu-0.mongodb-menu-headless.kubekitchen-prod.svc.cluster.local:27017/menudb"
  MONGO_ORDER_URI: "mongodb://mongodb-order-0.mongodb-order-headless.kubekitchen-prod.svc.cluster.local:27017/orderdb"