apiVersion: v1
kind: ConfigMap
metadata:
  name: kubekitchen-config
  namespace: kubekitchen-dev
  labels:
    project: kubekitchen
    environment: dev
data:
  NODE_ENV: "development"
  JWT_EXPIRES_IN: "7d"
  AUTH_PORT: "4001"
  RESTAURANT_PORT: "4002"
  MENU_PORT: "4003"
  ORDER_PORT: "4004"
  MENU_SERVICE_URL: "http://menu-service.kubekitchen-dev.svc.cluster.local:4003"