apiVersion: v1
kind: ConfigMap
metadata:
  name: kubekitchen-config
  namespace: kubekitchen-prod
  labels:
    project: kubekitchen
    environment: prod
data:
  NODE_ENV: "production"
  JWT_EXPIRES_IN: "1d"
  AUTH_PORT: "4001"
  RESTAURANT_PORT: "4002"
  MENU_PORT: "4003"
  ORDER_PORT: "4004"
  MENU_SERVICE_URL: "http://menu-service.kubekitchen-prod.svc.cluster.local:4003"