apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubekitchen-nfs
  labels:
    project: kubekitchen
provisioner: kubekitchen.io/nfs
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true