apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kgateway-class
  namespace: kgateway-system
spec:
  controllerName: kgateway.dev/kgateway
  description: "KGATEWAY for KubeKitchen"
