# Required for Gateway in kubekitchen-gateway to route
# to services in kubekitchen-dev namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: gateway-to-dev
  namespace: kubekitchen-dev
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: kubekitchen-gateway
  to:
    - group: ""
      kind: Service
---
# Required for Gateway in kubekitchen-gateway to route
# to services in kubekitchen-prod namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: gateway-to-prod
  namespace: kubekitchen-prod
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: kubekitchen-gateway
  to:
    - group: ""
      kind: Service